language: groovy

dist: xenial
install: true

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - openjdk11

script:
  - ./gradlew -version
  - travis_wait 5 ./gradlew test

# https://docs.travis-ci.com/user/languages/groovy/#gradle-caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/